apiVersion: apps/v1
kind: Deployment
metadata:
  name: store2018-inventoryservice
  labels:
    app: inventoryservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: inventoryservice
  template:
    metadata:
      labels:
        app: inventoryservice
    spec:
      containers:
      - name: inventoryservice
        image: jeremycookdev/inventoryservice:latest
        ports:
        - containerPort: 80