apiVersion: v1
kind: Secret
metadata:
  name: audit-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USER: admin
  DB_PASSWORD: Dentrix1
  SECURITY_JWT_SECRET: ReallyReallyReallyReallySecretKey
  SECURITY_HARD_CODED_SALT: EV8Imv85jH52UW3YVX1oTN3nZe0TZZhk34CeTl5p01ev22eGW6s88N5dL

