apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: splunk-persistance-claim
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
