apiVersion: v1
kind: Service
metadata:
  name: store2018-accountservice
  labels:
    app: accountservice
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: accountservice
  type: LoadBalancer
