apiVersion: v1
kind: Service
metadata:
  name: store2018-shoppingservice
  labels:
    app: shoppingservice
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: shoppingservice
  type: LoadBalancer
